# Generated by Django 4.2.25 on 2025-12-01 13:03

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPRESA', 'Empresa de Transporte'), ('CHOFER', 'Chofer'), ('FRONTERA', 'Agente de Frontera')], default='EMPRESA', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('peso_aprox', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=15, unique=True)),
                ('licencia_nro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='novedades/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('capacidad', models.FloatField(help_text='Capacidad máxima en toneladas')),
                ('consumo_promedio', models.FloatField(default=0, help_text='Consumo estimado (litros/km)')),
                ('costo_km', models.FloatField(default=0, help_text='Costo operativo por km en ARS')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='transporte.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('lat_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat_destino', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon_destino', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField()),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('ubicacion_actual', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('distancia_km', models.FloatField(default=0)),
                ('kilometros_recorridos', models.FloatField(default=0)),
                ('duracion_horas', models.FloatField(default=0)),
                ('tiempo_total_horas', models.FloatField(default=0)),
                ('consumo_promedio', models.FloatField(default=0, help_text='Litros por 100 km')),
                ('velocidad_promedio', models.FloatField(default=0, help_text='km/h')),
                ('costo_estimado', models.FloatField(default=0)),
                ('costo_combustible', models.FloatField(default=0, help_text='Costo total de combustible en USD')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.carga')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.chofer')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.empresa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='transporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PosicionGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('velocidad', models.FloatField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='transporte.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(default='GPS', max_length=50)),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mantenimiento', 'En Mantenimiento')], default='offline', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='transporte.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='ControlFrontera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_cruce', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('agente', models.ForeignKey(limit_choices_to={'rol': 'FRONTERA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='transporte.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='chofer',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choferes', to='transporte.empresa'),
        ),
        migrations.AddField(
            model_name='carga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='transporte.empresa'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEMORA', 'Demora'), ('DESVIO', 'Desvío de ruta'), ('OTRO', 'Otro')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='transporte.viaje')),
            ],
        ),
    ]
