# Generated by Django 5.2.7 on 2025-11-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroubicacion',
            name='viaje',
        ),
        migrations.RemoveField(
            model_name='rutademo',
            name='viaje',
        ),
        migrations.DeleteModel(
            name='PosicionDemo',
        ),
        migrations.DeleteModel(
            name='RegistroUbicacion',
        ),
        migrations.DeleteModel(
            name='RutaDemo',
        ),
        migrations.DeleteModel(
            name='ViajeDemo',
        ),
    ]
