# Generated by Django 5.2.7 on 2025-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='ubicacion_actual',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
