# Generated by Django 4.2.25 on 2025-11-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_viaje_ubicacion_actual_alter_viaje_codigo_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='transporte.viaje')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
