# Generated by Django 4.2.26 on 2025-11-26 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_usuario_photo_alter_viaje_lat_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='novedades/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveField(
            model_name='posiciongps',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='posiciongps',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posiciongps',
            name='velocidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posiciongps',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.viaje'),
        ),
    ]
