# Generated by Django 5.2.7 on 2025-11-29 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_remove_registroubicacion_viaje_remove_rutademo_viaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiciongps',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='transporte.viaje'),
        ),
    ]
