# Generated by Django 5.2.7 on 2025-11-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_novedad_remove_posiciongps_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroubicacion',
            name='viaje',
        ),
        migrations.RemoveField(
            model_name='rutademo',
            name='viaje',
        ),
        migrations.AlterField(
            model_name='posiciongps',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='transporte.viaje'),
        ),
        migrations.DeleteModel(
            name='PosicionDemo',
        ),
        migrations.DeleteModel(
            name='RegistroUbicacion',
        ),
        migrations.DeleteModel(
            name='RutaDemo',
        ),
        migrations.DeleteModel(
            name='ViajeDemo',
        ),
    ]
