# Generated by Django 5.2.7 on 2025-12-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_alter_posiciongps_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='litros_consumidos',
            field=models.FloatField(default=0, help_text='Litros de combustible utilizados en el viaje'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio_combustible',
            field=models.FloatField(default=1.5, help_text='Precio por litro en USD'),
        ),
    ]
