# Generated by Django 4.2.25 on 2025-11-11 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_registroubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViajeDemo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: San Salvador → Perico', max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Orden del punto en la ruta')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='transporte.viajedemo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PosicionDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='transporte.viajedemo')),
            ],
        ),
    ]
