# Generated by Django 5.2.7 on 2025-11-12 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_viajedemo_rutademo_posiciondemo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posiciondemo',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='posiciondemo',
            old_name='fecha_hora',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='viajedemo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='viajedemo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='viajedemo',
            name='destino',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viajedemo',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='viajedemo',
            name='origen',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viajedemo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
