# Generated by Django 4.2.25 on 2025-11-13 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_viajedemo_rutademo_posiciondemo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posiciondemo',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='posiciondemo',
            old_name='fecha_hora',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='viajedemo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='viajedemo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='consumo_promedio',
            field=models.FloatField(default=0, help_text='Consumo estimado (litros/km)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='costo_km',
            field=models.FloatField(default=0, help_text='Costo operativo por km en ARS'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='costo_estimado',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='distancia_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='duracion_horas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='viajedemo',
            name='destino',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viajedemo',
            name='estado',
            field=models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado')], default='PROGRAMADO', max_length=20),
        ),
        migrations.AddField(
            model_name='viajedemo',
            name='origen',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viajedemo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
