# Generated by Django 4.2.25 on 2025-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0005_alter_posiciondemo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='consumo_promedio',
            field=models.FloatField(default=0, help_text='Litros por 100 km'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='costo_combustible',
            field=models.FloatField(default=0, help_text='Costo total de combustible en USD'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='kilometros_recorridos',
            field=models.FloatField(default=0, help_text='Distancia total del viaje en km'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='lat_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='lat_origen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='lon_destino',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='lon_origen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='tiempo_total_horas',
            field=models.FloatField(default=0, help_text='Duración total en horas'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='velocidad_promedio',
            field=models.FloatField(default=0, help_text='Velocidad promedio en km/h'),
        ),
    ]
