# Generated by Django 4.2.25 on 2025-11-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0006_viaje_consumo_promedio_viaje_costo_combustible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(default='GPS', max_length=50)),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('mantenimiento', 'En Mantenimiento')], default='offline', max_length=20)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='transporte.vehiculo')),
            ],
        ),
    ]
